# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a929ba4503c7e5111b954ff710d2ca4169cf37a596ea890eb827b8fa36ecc5443b73b627a7c83a90bba4270448ab87c6f25be1ebad7dc686a71d956f170ab34

test:
  secret_key_base: 53c16c9ceb5202dc70a8178726a3a32bac09bc60508a3bae5a26e5cda9dd06b391aa2e197cbfaa8c2524ada8b15f938aebc5ded625e3d1928c5bd7064580c553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
